version: "3"
services:
  backend-nodejs:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
    ports:
      - 8080:8080
    volumes:
      - ./:/app/
      - nodemodules:/app/node_modules
    networks:
      - inventory_tiki
    stdin_open: true
    tty: true

  frontend-reactjs:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/app
      - nodemodules:/app/node_modules
    networks:
      - inventory_tiki
    stdin_open: true

  database-mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "inventory_tiki"
      MYSQL_DATABASE: "inventory_tiki"
      MYSQL_USER: "tuan"
      MYSQL_PASSWORD: "tuan_inventory"
    networks:
      - inventory_tiki

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3080:80"
    depends_on:
      - backend-nodejs
      - frontend-reactjs
    networks:
      - inventory_tiki

networks:
  inventory_tiki:
    driver: bridge
volumes:
  nodemodules: {}
