version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    expose:
      - 8080
    volumes:
      - /app/node_modules
      - ./backend:/app/
    networks:
      - inventory_tiki
    restart: on-failure
    stdin_open: true
    tty: true

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - inventory_tiki

networks:
  inventory_tiki:
    driver: bridge
volumes:
  nodemodules: {}
  mongodb:
