version: "3"
services:
  nginx:
    depends_on:
      - auth
    restart: always # because it is routing traffic to our entire app
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
    networks:
      - inventory_tiki

  auth:
    build:
      context: ./auth
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      SESSION_KEY: "${SESSION_KEY}"
      ACCESS_TOKEN_PUBLIC_KEY: "${ACCESS_TOKEN_PUBLIC_KEY}"
      ACCESS_TOKEN_PRIVATE_KEY: "${ACCESS_TOKEN_PRIVATE_KEY}"
    volumes:
      - /app/node_modules
      - ./auth:/app/
    networks:
      - inventory_tiki
    restart: on-failure
    stdin_open: true
    tty: true

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongodb:/data/db
    networks:
      - inventory_tiki

networks:
  inventory_tiki:
    driver: bridge
volumes:
  nodemodules: {}
  mongodb:
